# Generated by Django 5.0.6 on 2024-06-19 14:53

import web_master_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='app_logo',
            field=models.ImageField(upload_to=web_master_api.models.upload_path),
        ),
    ]
