# Generated by Django 5.0.6 on 2024-06-27 15:18

import web_master_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0005_rename_title_menu_menu_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_icon',
            field=models.ImageField(upload_to=web_master_api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='websitedetail',
            name='site_logo',
            field=models.ImageField(upload_to=web_master_api.models.upload_path),
        ),
    ]
