# Generated by Django 5.0.6 on 2024-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0006_notification_alter_menuitem_menu_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_app_id', models.CharField(max_length=100)),
                ('android_app_id', models.CharField(max_length=100)),
                ('show_bannar_ad_android', models.BooleanField(default=False)),
                ('show_bannar_ad_ios', models.BooleanField(default=False)),
            ],
        ),
    ]
