# Generated by Django 5.0.6 on 2024-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0007_addmob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmob',
            name='android_app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addmob',
            name='ios_app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
