# Generated by Django 5.0.6 on 2024-06-29 07:06

import web_master_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0008_alter_addmob_android_app_id_alter_addmob_ios_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to=web_master_api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='app_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='primary_color',
            field=models.CharField(max_length=100),
        ),
    ]
