# Generated by Django 5.0.6 on 2024-11-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_master_api', '0009_remove_appconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='menu_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
